/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/metrics/prom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Endpoint that serves Prometheus metrics.
         */
        get: operations["metrics_metrics_prom_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health check endpoint — used by monitoring systems to verify the API is running.
         *
         *     Returns a simple JSON object with status. This is a standard practice:
         *     load balancers and orchestration systems (Kubernetes, Docker Compose)
         *     call this endpoint to check if the service is healthy.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/autocomplete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Autocomplete
         * @description Get autocomplete suggestions for a given text.
         *
         *     This is the primary endpoint — it takes text input and returns
         *     the most likely next words based on the selected language model.
         *
         *     HOW IT WORKS:
         *     1. Tokenize the input text (split into words, lowercase, handle punctuation)
         *     2. Select the requested model (n-gram or Markov chain)
         *     3. Ask the model for top-k next-word predictions
         *     4. Return predictions with probabilities
         *
         *     Args:
         *         req: AutocompleteRequest with text, top_k, and model selection.
         *
         *     Returns:
         *         AutocompleteResponse with suggestions, context, and model name.
         */
        post: operations["autocomplete_autocomplete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/autocomplete/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Autocomplete Batch
         * @description Batch autocomplete — get predictions for multiple texts at once.
         *
         *     BATCH PROCESSING is more efficient than making N individual requests:
         *     - Reduces HTTP overhead (1 request instead of N)
         *     - Models are loaded/cached once
         *     - Easier for clients to manage
         *
         *     Use this when you need predictions for many texts, e.g., processing
         *     a document line-by-line or a search query log.
         *
         *     Args:
         *         req: BatchRequest with list of texts and model settings.
         *
         *     Returns:
         *         BatchResponse with predictions for each input text.
         */
        post: operations["autocomplete_batch_autocomplete_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description List available language models with their descriptions.
         *
         *     This endpoint helps API consumers discover what models are available
         *     and choose the right one for their use case.
         */
        get: operations["list_models_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Text
         * @description Generate text using the Markov chain model.
         *
         *     TEXT GENERATION is a natural extension of autocomplete — instead of
         *     predicting ONE next word, we iteratively predict many words to produce
         *     coherent (or creative) text passages.
         *
         *     The temperature parameter controls the randomness:
         *     - 0.1: Very deterministic, repeats common patterns
         *     - 1.0: Natural diversity, balanced between common and rare words
         *     - 2.0+: Wild and creative, may produce unusual word combinations
         *
         *     Try it: generate with temperature=0.3 vs temperature=2.0 and compare!
         *
         *     Args:
         *         req: GenerateRequest with start_word, max_length, and temperature.
         *
         *     Returns:
         *         GenerateResponse with the generated text and metadata.
         */
        post: operations["generate_text_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Get API usage metrics (hand-rolled JSON format).
         *
         *     Returns request counts, rate limit hits, and endpoint-level breakdowns.
         *     Useful for quick human inspection and for the React Metrics page.
         *
         *     For a scrape-friendly format, install prometheus-fastapi-instrumentator
         *     and hit /metrics/prom — that endpoint speaks the Prometheus exposition
         *     format and adds latency histograms out of the box.
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocab/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vocab Stats
         * @description Get vocabulary statistics for the trained models.
         *
         *     Returns information about the training corpus and vocabulary size,
         *     useful for understanding the model's coverage and limitations.
         */
        get: operations["vocab_stats_vocab_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AutocompleteRequest
         * @description Request body for the autocomplete endpoint.
         *
         *     Attributes:
         *         text: The input text to get completions for.
         *         top_k: Number of suggestions to return (1-20).
         *         model: Which language model to use.
         */
        AutocompleteRequest: {
            /**
             * Text
             * @description Input text to complete. Last few words are used as context.
             * @example machine learning is a
             * @example the attention mechanism
             * @example deep learning
             */
            text: string;
            /**
             * Top K
             * @description Number of suggestions to return.
             * @default 5
             */
            top_k: number;
            /**
             * Model
             * @description Language model to use: 'ngram', 'markov', or (when PyTorch is installed) 'lstm' / 'transformer'. Selecting a neural model on a minimal install returns 503.
             * @default ngram
             */
            model: string;
            /**
             * Tokenizer
             * @description Tokenizer flavour: 'word' (default) uses the project's whitespace+regex tokenizer; 'bpe' wires in a byte-level BPE tokenizer (needs the optional 'transformers' package, and only valid with model='lstm' or 'transformer').
             * @default word
             */
            tokenizer: string;
            /**
             * Tokenizer Name
             * @description Optional HF repo for the BPE tokenizer (e.g. 'gpt2'). Ignored when tokenizer='word'. Defaults to SmolLM2's tokenizer so the first BPE request doesn't force a new download. Different names are cached independently.
             */
            tokenizer_name?: string | null;
        };
        /**
         * AutocompleteResponse
         * @description Response body for the autocomplete endpoint.
         */
        AutocompleteResponse: {
            /**
             * Suggestions
             * @description Top-k word suggestions.
             */
            suggestions: components["schemas"]["Suggestion"][];
            /**
             * Context
             * @description The context words used for prediction.
             */
            context: string;
            /**
             * Model
             * @description Which model generated these suggestions.
             */
            model: string;
        };
        /**
         * BatchRequest
         * @description Request body for batch autocomplete.
         */
        BatchRequest: {
            /**
             * Texts
             * @description List of input texts to complete. Each text is capped at 1000 characters to match the single-text endpoint.
             */
            texts: string[];
            /**
             * Top K
             * @default 5
             */
            top_k: number;
            /**
             * Model
             * @default ngram
             */
            model: string;
            /**
             * Tokenizer
             * @default word
             */
            tokenizer: string;
            /** Tokenizer Name */
            tokenizer_name?: string | null;
        };
        /**
         * BatchResponse
         * @description Response body for batch autocomplete.
         */
        BatchResponse: {
            /**
             * Results
             * @description Predictions for each input text.
             */
            results: components["schemas"]["AutocompleteResponse"][];
        };
        /**
         * GenerateRequest
         * @description Request body for text generation endpoint.
         */
        GenerateRequest: {
            /**
             * Start Word
             * @description Word to start generation from. If omitted, picks a common starting word.
             */
            start_word?: string | null;
            /**
             * Max Length
             * @description Maximum number of words to generate.
             * @default 20
             */
            max_length: number;
            /**
             * Temperature
             * @description Sampling temperature: <1.0 = focused, 1.0 = natural, >1.0 = creative.
             * @default 1
             */
            temperature: number;
            /**
             * Seed
             * @description Random seed for reproducible generation.
             */
            seed?: number | null;
        };
        /**
         * GenerateResponse
         * @description Response body for text generation.
         */
        GenerateResponse: {
            /**
             * Text
             * @description Generated text.
             */
            text: string;
            /**
             * Word Count
             * @description Number of words generated.
             */
            word_count: number;
            /**
             * Temperature
             * @description Temperature used for generation.
             */
            temperature: number;
            /**
             * Model
             * @description Model used for generation.
             * @default markov
             */
            model: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Suggestion
         * @description A single autocomplete suggestion with its probability.
         */
        Suggestion: {
            /**
             * Word
             * @description The suggested next word.
             */
            word: string;
            /**
             * Probability
             * @description Probability of this suggestion.
             */
            probability: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    metrics_metrics_prom_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    autocomplete_autocomplete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutocompleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutocompleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    autocomplete_batch_autocomplete_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    generate_text_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    vocab_stats_vocab_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
